/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    EntryPage: typeof import('./src/components/EntryPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    MailAcitvation: typeof import('./src/components/MailAcitvation.vue')['default']
    MailActivation: typeof import('./src/components/MailActivation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
    UserInput: typeof import('./src/components/UserInput.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}
